title: ItgwO's Blog
author: ItgwO
email: your-email@domain.com
description: ItgwO's blog is created with jekyll
theme: jekyll-theme-minimal
# social links
twitter_username: your-twitter-handle
github_username:  ItgwO

show_excerpts: true # set to false to remove excerpts on the homepage
